### ISSUE TITLE
Add other translate APIs?

### ISSUE THREAD

**Issue by A-nony-mous** [SakiRinn/LiveCaptions-Translator#3]
### 

Can we add more translate apis like Google or Bings?

-----

可以尝试加入谷歌、Bing等的其他翻译API吗？

**Comment by SakiRinn** [comment]
> Can we add more translate apis like Google or Bings?
> 
> 可以尝试加入谷歌、Bing等的其他翻译API吗？

可以的，我之后更新一下

**Comment by A-nony-mous** [comment]
> > Can we add more translate apis like Google or Bings?
> > 可以尝试加入谷歌、Bing等的其他翻译API吗？
> 
> 可以的，我之后更新一下

I also implemented Google translate in a magic api(?). I will make another PR.
***
谷歌翻译从网上找了个奇怪的接口（？）也实现了，我再给你提一条pr
