### ISSUE TITLE
Add support for ARM64

### ISSUE THREAD

**Issue by A-nony-mous** [SakiRinn/LiveCaptions-Translator#8]
Currently this app only builds for x64 and might require installing x64 .NET on arm64 devices. Hope we can support builds for ARM64.

**Comment by A-nony-mous** [comment]
#7

**Comment by SakiRinn** [comment]
Thank you for your contribution!
By the way, I recently had some personal matters to attend to, leaving me with no time to modify the code. I will soon resume updating it. Thank you very much for your PRs during this time!
